import { useEffect, useState } from "react";
import { api } from "../lib/api.js";
const arr = (v) => Array.isArray(v) ? v.join(", ") : v || "";
export default function ProfileForm({ onSaved }) {
  const [form,setForm]=useState(null); const [saved,setSaved]=useState(false);
  useEffect(()=>{api("/profile").then(r=>setForm({...r.data,skills:arr(r.data.skills),targetRoles:arr(r.data.targetRoles),preferredLocations:arr(r.data.preferredLocations),excludedKeywords:arr(r.data.excludedKeywords)}));},[]);
  if(!form)return <div className="panel">Loading profile…</div>;
  const set=(k,v)=>setForm({...form,[k]:v});
  async function save(e){e.preventDefault();const body={...form,skills:form.skills.split(",").map(x=>x.trim()).filter(Boolean),targetRoles:form.targetRoles.split(",").map(x=>x.trim()).filter(Boolean),preferredLocations:form.preferredLocations.split(",").map(x=>x.trim()).filter(Boolean),excludedKeywords:form.excludedKeywords.split(",").map(x=>x.trim()).filter(Boolean)};await api("/profile",{method:"PUT",body:JSON.stringify(body)});setSaved(true);setTimeout(()=>setSaved(false),1500);onSaved?.();}
  return <form className="panel stack" onSubmit={save}><div className="section-head"><div><span className="eyebrow">Candidate data</span><h2>Your matching profile</h2></div>{saved&&<span className="chip good">Saved</span>}</div><div className="form-grid two">
    <input placeholder="First name" value={form.firstName||""} onChange={e=>set("firstName",e.target.value)}/><input placeholder="Last name" value={form.lastName||""} onChange={e=>set("lastName",e.target.value)}/><input placeholder="Email" value={form.email||""} onChange={e=>set("email",e.target.value)}/><input placeholder="Phone" value={form.phone||""} onChange={e=>set("phone",e.target.value)}/><input placeholder="City" value={form.city||""} onChange={e=>set("city",e.target.value)}/><input placeholder="Current title" value={form.currentTitle||""} onChange={e=>set("currentTitle",e.target.value)}/><input type="number" min="0" step="0.5" placeholder="Years experience" value={form.yearsExperience??""} onChange={e=>set("yearsExperience",Number(e.target.value))}/><input placeholder="Notice period" value={form.noticePeriod||""} onChange={e=>set("noticePeriod",e.target.value)}/><input placeholder="Current CTC" value={form.currentCTC||""} onChange={e=>set("currentCTC",e.target.value)}/><input placeholder="Expected CTC" value={form.expectedCTC||""} onChange={e=>set("expectedCTC",e.target.value)}/><input placeholder="LinkedIn URL" value={form.linkedin||""} onChange={e=>set("linkedin",e.target.value)}/><input placeholder="GitHub URL" value={form.github||""} onChange={e=>set("github",e.target.value)}/><input placeholder="Portfolio URL" value={form.portfolio||""} onChange={e=>set("portfolio",e.target.value)}/><input placeholder="Visa/sponsorship answer" value={form.sponsorshipAnswer||""} onChange={e=>set("sponsorshipAnswer",e.target.value)}/>
  </div><label>Skills<textarea value={form.skills} onChange={e=>set("skills",e.target.value)} /></label><label>Target roles<textarea value={form.targetRoles} onChange={e=>set("targetRoles",e.target.value)} /></label><label>Preferred locations<textarea value={form.preferredLocations} onChange={e=>set("preferredLocations",e.target.value)} /></label><label>Exclude keywords<textarea value={form.excludedKeywords} onChange={e=>set("excludedKeywords",e.target.value)} /></label><label>Short professional summary<textarea rows="4" value={form.about||""} onChange={e=>set("about",e.target.value)} /></label><button className="primary-btn large">Save profile</button></form>;
}
