import { useCallback, useEffect, useState } from "react";
import { api } from "./lib/api.js";
import StatCard from "./components/StatCard.jsx";
import JobCard from "./components/JobCard.jsx";
import ProfileForm from "./components/ProfileForm.jsx";
import ResumeManager from "./components/ResumeManager.jsx";
import SourcesPanel from "./components/SourcesPanel.jsx";
import DiscoveryPanel from "./components/DiscoveryPanel.jsx";
import EmailPanel from "./components/EmailPanel.jsx";

export default function App() {
  const [tab,setTab]=useState("jobs"),[jobs,setJobs]=useState([]),[stats,setStats]=useState({}),[status,setStatus]=useState("all"),[sourceType,setSourceType]=useState("all"),[minScore,setMinScore]=useState(60),[query,setQuery]=useState(""),[error,setError]=useState("");
  const refresh=useCallback(async()=>{try{setError("");const p=new URLSearchParams({status,sourceType,minScore:String(minScore),q:query,limit:"300"});const [j,s]=await Promise.all([api(`/jobs?${p}`),api("/stats")]);setJobs(j.data);setStats(s.data);}catch(e){setError(e.message)}},[status,sourceType,minScore,query]);
  useEffect(()=>{refresh();},[refresh]);
  async function updateStatus(id,nextStatus){await api(`/jobs/${id}/status`,{method:"PATCH",body:JSON.stringify({status:nextStatus})});refresh();}
  const tabs=[['jobs','Matches'],['discover','Discover'],['sources','Sources'],['resumes','Resumes'],['profile','Profile'],['email','Email signals']];
  return <div className="app-shell"><header className="topbar"><div className="brand"><div className="brand-mark">A</div><div><strong>ApplyPilot AI</strong><span>Daily job-search copilot</span></div></div><nav>{tabs.map(([k,l])=><button key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}>{l}</button>)}</nav></header><main>
    <section className="hero"><div><div className="eyebrow">Version 4 · lower-competition-first workflow</div><h1>Your strongest roles, already sorted.</h1><p>Collect jobs from public ATS feeds and search discovery, rank them against your profile, choose the right resume, generate application answers and autofill repetitive fields.</p></div><div className="hero-badge"><span>Final submission</span><strong>Always reviewed by you</strong></div></section>
    <section className="stats-grid"><StatCard label="Tracked" value={stats.total??0} hint="All discovered jobs"/><StatCard label="Today" value={stats.today??0} hint="Newly discovered"/><StatCard label="75%+ matches" value={stats.strong??0} hint="Priority shortlist"/><StatCard label="Applied" value={stats.applied??0} hint="Submitted applications"/><StatCard label="Interviews" value={stats.interviews??0} hint="Pipeline progress"/></section>
    {tab==='jobs'&&<><section className="toolbar panel"><input placeholder="Search title, company, location…" value={query} onChange={e=>setQuery(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="new">New</option><option value="shortlisted">Shortlisted</option><option value="applied">Applied</option><option value="interview">Interview</option><option value="offer">Offer</option><option value="rejected">Rejected</option><option value="skipped">Skipped</option></select><select value={sourceType} onChange={e=>setSourceType(e.target.value)}><option value="all">All sources</option><option value="linkedin">LinkedIn</option><option value="indeed">Indeed</option><option value="naukri">Naukri</option><option value="wellfound">Wellfound</option><option value="cutshort">Cutshort</option><option value="instahyre">Instahyre</option><option value="hirist">Hirist</option><option value="yc">YC Startups</option><option value="greenhouse">Greenhouse</option><option value="lever">Lever</option><option value="ashby">Ashby</option><option value="workable">Workable</option></select><label className="score-filter">Min <input type="range" min="0" max="100" step="5" value={minScore} onChange={e=>setMinScore(Number(e.target.value))}/><strong>{minScore}%</strong></label><button onClick={refresh}>Refresh</button></section>{error&&<div className="error-box">{error}</div>}<section className="jobs-grid">{jobs.map(j=><JobCard key={j._id} job={j} onStatus={updateStatus}/>)}{!jobs.length&&!error&&<div className="empty-state"><h3>No jobs in this view</h3><p>Run discovery, add ATS sources, or lower the score threshold.</p></div>}</section></>}
    {tab==='discover'&&<DiscoveryPanel onDone={refresh}/>} {tab==='sources'&&<SourcesPanel onChange={refresh}/>} {tab==='resumes'&&<ResumeManager/>} {tab==='profile'&&<ProfileForm onSaved={refresh}/>} {tab==='email'&&<EmailPanel/>}
  </main><footer>ApplyPilot AI v2 · Local-first · No CAPTCHA bypass · Final application submission stays under your control.</footer></div>;
}
