const mongoose = require('mongoose');

/**
 * Zomato Table Reservation model.
 *
 * Field names mirror the exact keys described in:
 *   "Table Reservation - Oniro.pdf"
 *
 * Inbound (Booking Relay webhook from Zomato):
 *   booking_id, table_reservation.*, customer_details.*, business_details.*,
 *   offer_details.*, created_at
 *
 * Outbound (our response / Zomato Accept/Reject APIs):
 *   partner_booking_id, booking_status, reason
 */

const CoverChargeSchema = new mongoose.Schema(
  {
    value: { type: Number, default: 0 },
    currency_code: { type: String, default: 'INR' },
  },
  { _id: false }
);

const TableReservationSchema = new mongoose.Schema(
  {
    slot_start_time: { type: Number, required: true },   // epoch seconds
    duration: { type: Number, default: 60 },              // minutes
    covers_count: { type: Number, required: true },
    notes: { type: [String], default: [] },
    preferred_confirmation_mode: {
      type: String,
      enum: ['AUTO', 'MANUAL'],
      default: 'MANUAL',
    },
    cover_charge: { type: CoverChargeSchema, default: () => ({}) },
  },
  { _id: false }
);

const CustomerDetailsSchema = new mongoose.Schema(
  {
    name: { type: String, default: '' },
    contact_number: { type: String, default: '' },
    email_address: { type: String, default: '' },
    visit_count: { type: String, default: '' },
    contact_number_with_isd_code: { type: String, default: '' },
  },
  { _id: false }
);

const BusinessDetailsSchema = new mongoose.Schema(
  {
    zomato_business_id: { type: String, default: '' },
    store_id: { type: String, required: true },
  },
  { _id: false }
);

/**
 * Per "Table Reservation - Oniro.pdf" Get Booking Details response:
 * offer_details.offers[] each has offer_value, offer_type, offer_verbose, offer_message.
 * offer_type values: PRE-BOOK | FREEBIE | GOLD
 */
const OfferItemSchema = new mongoose.Schema(
  {
    offer_value: { type: Number, default: 0 },
    offer_type: { type: String, enum: ['PRE-BOOK', 'FREEBIE', 'GOLD', ''], default: '' },
    offer_verbose: { type: String, default: '' },
    offer_message: { type: String, default: '' },
  },
  { _id: false }
);

const OfferDetailsSchema = new mongoose.Schema(
  {
    discount_percentage: { type: Number, default: 0 },
    offers: { type: [OfferItemSchema], default: [] },
    offer_message: { type: String, default: '' },
  },
  { _id: false }
);

const ZomatoReservationSchema = new mongoose.Schema(
  {
    /** The internal store document this booking belongs to */
    store: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Store',
      required: true,
    },

    /** booking_id — Zomato's unique booking identifier */
    zomato_booking_id: {
      type: String,
      required: true,
      unique: true,
      trim: true,
    },

    /**
     * partner_booking_id — generated by us, returned to Zomato in the
     * booking relay response and used in Accept / Reject calls.
     */
    partner_booking_id: {
      type: String,
      required: true,
      unique: true,
      trim: true,
    },

    /**
     * booking_status — mirrors Zomato booking_status values:
     *   AWAITING_CONFIRMATION | CONFIRMED | CANCELLED | REJECTED | FAILED | REDEEMED
     *
     * We set it to AWAITING_CONFIRMATION on receipt.
     * On MANUAL mode the restaurant must Accept or Reject from the dashboard.
     * On AUTO mode we immediately call Zomato Accept API and set CONFIRMED.
     */
    booking_status: {
      type: String,
      enum: ['AWAITING_CONFIRMATION', 'CONFIRMED', 'CANCELLED', 'REJECTED', 'FAILED', 'REDEEMED'],
      default: 'AWAITING_CONFIRMATION',
    },

    /** Rejection reason when booking_status == REJECTED */
    rejection_reason: { type: String, default: '' },

    table_reservation: { type: TableReservationSchema, required: true },
    customer_details: { type: CustomerDetailsSchema, default: () => ({}) },
    business_details: { type: BusinessDetailsSchema, required: true },
    offer_details: { type: OfferDetailsSchema, default: () => ({}) },

    /** Epoch timestamp from Zomato's created_at field */
    zomato_created_at: { type: Number, default: null },

    /** Full raw payload from Zomato for debugging */
    raw_payload: { type: mongoose.Schema.Types.Mixed, default: null },
  },
  { timestamps: true }
);

ZomatoReservationSchema.index({ store: 1, booking_status: 1, 'table_reservation.slot_start_time': -1 });

module.exports = mongoose.model('ZomatoReservation', ZomatoReservationSchema);
